name: Build, Test, and Deploy a container to an Azure Web App using Docker Hub

env:
    AZURE_WEBAPP_NAME: mainstack # set this to the name of your Azure Web App
    DOCKER_HUB_REPO: ${{ secrets.DOCKER_USERNAME }}/mainstack # replace with your Docker Hub username and repo

on:
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16"

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

    build:
        runs-on: ubuntu-latest
        needs: test # Ensure tests are executed before the build
        steps:
            - uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: docker.io
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

            - name: Build and push container image to Docker Hub
              uses: docker/build-push-action@v5
              with:
                  push: true
                  tags: ${{ env.DOCKER_HUB_REPO }}:${{ github.sha }}
                  file: ./Dockerfile

    deploy:
        permissions:
            contents: none
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Development"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                  app-name: ${{ env.AZURE_WEBAPP_NAME }}
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  images: "docker.io/${{ env.DOCKER_HUB_REPO }}:${{ github.sha }}"
